#ifndef PAGE_INDEX_H
#define PAGE_INDEX_H

const static char IndexHtml[] PROGMEM =
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>RHINO LUX PVT LTD</title><style>"
"body{font-family:Arial,sans-serif;background-color:aliceblue;margin:0;padding:0}"
".container{max-width:420px;margin:40px auto;background:#f8f8f8;padding:22px;"
"border-radius:10px;box-shadow:0 6px 20px rgba(0,0,0,.5);color:#fff}"
".logo{text-align:center;margin-bottom:15px}"
".logo img{max-width:160px}"
"h2{text-align:center;margin-bottom:20px;font-weight:600;color:#0b0b0b}"
"label{font-size:13px;display:block;margin-top:12px;color:#050505}"
"input{width:100%;padding:9px;margin-top:5px;box-sizing:border-box;"
"border-radius:6px;border:1px solid #2a2a2a;background-color:#fff;color:#000}"
"input:focus{outline:none;border-color:#7a3cff}"
"button{width:100%;margin-top:15px;padding:11px;"
"background:linear-gradient(135deg,#3a3db8,#7a3cff);color:#fff;"
"border:none;border-radius:8px;font-size:15px;font-weight:600;cursor:pointer;"
"transition:transform .1s ease,box-shadow .1s ease}"
"button.secondary{background:linear-gradient(135deg,#5b2aa8,#8f3ddb)}"
"button:hover{transform:translateY(-1px);box-shadow:0 4px 10px rgba(122,60,255,.4)}"
"</style></head><body onload=\"getPrice()\">"
"<div class=\"container\">"
"<div class=\"logo\"><img src=\"icon.png\" alt=\"App Logo\"></div>"
// "<button type=\"button\" onclick=\"getPrice()\">Retrieve Prices</button>"
"<label>PDU ID</label><input type=\"text\" id=\"pduid\" value=\"--\" readonly>"
"<label>Petrol</label><input type=\"number\" id=\"petrol\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>Diesel</label><input type=\"number\" id=\"diesel\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>Power</label><input type=\"number\" id=\"power\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>Auto LPG</label><input type=\"number\" id=\"autolpg\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>TurboJet</label><input type=\"number\" id=\"turbojet\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>Power99</label><input type=\"number\" id=\"power99\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>CNG</label><input type=\"number\" id=\"cng\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>Power95</label><input type=\"number\" id=\"power95\" step=\".01\" min=\"0\" max=\"199.99\" value=\"0.00\">"
"<label>Message</label><input type=\"text\" id=\"msg\" placeholder=\"Write message here\" maxlength=\"50\">"
"<button class=\"secondary\" type=\"button\" onclick=\"formToUpdate()\">Update</button>"
"<button class=\"secondary\" type=\"button\" onclick=\"goToAdvSet()\">Settings</button>"
"</div>"

"<script>"
"function getPrice(){"
"var pdu=document.getElementById('pduid');"
"var petr2=document.getElementById('petrol');"
"var dies2=document.getElementById('diesel');"
"var powe2=document.getElementById('power');"
"var pow952=document.getElementById('power95');"
"var pow992=document.getElementById('power99');"
"var tuje2=document.getElementById('turbojet');"
"var aulp2=document.getElementById('autolpg');"
"var cng2=document.getElementById('cng');"
"var request=new XMLHttpRequest();"
"request.open('GET','/get_price');request.send();"
"request.onload=function(){"
"if(request.status==200){"
"var j=JSON.parse(request.responseText);"
"pdu.value=j.PDUID;"
"msg.value=j.MSG;"
"petr2.value=j.item1[0]=='0'?j.item1.slice(1):j.item1;"
"dies2.value=j.item2[0]=='0'?j.item2.slice(1):j.item2;"
"powe2.value=j.item3[0]=='0'?j.item3.slice(1):j.item3;"
"pow952.value=j.item4[0]=='0'?j.item4.slice(1):j.item4;"
"pow992.value=j.item5[0]=='0'?j.item5.slice(1):j.item5;"
"tuje2.value=j.item6[0]=='0'?j.item6.slice(1):j.item6;"
"aulp2.value=j.item7[0]=='0'?j.item7.slice(1):j.item7;"
"cng2.value=j.item8[0]=='0'?j.item8.slice(1):j.item8;"
"alert('Fetched last updated prices successfully');"
"}else{alert('Error: Connect to the Device.');}}"
"}"

"function checkValue(f){"
"if(isNaN(f))return '000.00';"
"if(f<0||f>999.99)return 'voidvalue';"
"var p=Math.round(f*100);var s=(p%10);"
"p=Math.floor(p/10);s='.'+(p%10)+s;"
"p=Math.floor(p/10);s=(p%10)+s;"
"p=Math.floor(p/10);s=(p%10)+s;"
"p=Math.floor(p/10);s=(p%10)+s;"
"return s;}"

"function dateBuilder(){var d=new Date();"
"var dd=('0'+d.getDate()).slice(-2);"
"var mm=('0'+(d.getMonth()+1)).slice(-2);"
"return dd+'/'+mm+'/'+d.getFullYear();}"

"function timeBuilder(){var t=new Date();"
"return ('0'+t.getHours()).slice(-2)+'-'"
"+('0'+t.getMinutes()).slice(-2)+'-'"
"+('0'+t.getSeconds()).slice(-2);}"

"function goToAdvSet(){window.location='setting_login_page';}"

"function formToUpdate(){"
"var p=checkValue(parseFloat(document.getElementById('petrol').value));"
"var d=checkValue(parseFloat(document.getElementById('diesel').value));"
"var w=checkValue(parseFloat(power.value));"
"var w95=checkValue(parseFloat(power95.value));"
"var w99=checkValue(parseFloat(power99.value));"
"var t=checkValue(parseFloat(turbojet.value));"
"var a=checkValue(parseFloat(autolpg.value));"
"var c=checkValue(parseFloat(cng.value));"
"var m=msg.value;"
"if(m.length>50){alert('Message should not exceed 50 characters.');return;}"
"if([p,d,w,w95,w99,t,a,c].includes('voidvalue')){"
"alert('Please check the prices entered.');return;}"
"var data='{'+"
"'\"item1\":\"'+p+'\",\"item2\":\"'+d+'\",\"item3\":\"'+w+'\",'+"
"'\"item4\":\"'+a+'\",\"item5\":\"'+t+'\",\"item6\":\"'+w99+'\",'+"
"'\"item7\":\"'+c+'\",\"item8\":\"'+w95+'\",\"MSG\":\"'+m+'\",'+"
"'\"date\":\"'+dateBuilder()+'\",\"time\":\"'+timeBuilder()+'\"}';"
"var x=new XMLHttpRequest();x.open('POST','/set_price');"
"x.onload=function(){"
"if(x.status==200){alert('Updated successfully');}"
"else{alert('Request failed');}};"
"x.send(data);}"
"</script>"
"</body>"
"</html>";

#endif