#ifndef PAGE_LOGIN_H
#define PAGE_LOGIN_H

const static char LoginHtml[] PROGMEM =
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>User Login</title><style>"
"body{font-family:Arial,sans-serif;background-color:aliceblue;margin:0;padding:20px}"
".container{max-width:450px;margin:auto;padding:20px;border-radius:20px;"
"box-sizing:border-box;box-shadow:5px 10px 18px rgba(0,0,0,.5);"
"background-color:#fff;color:#ffffffc5}"
".container div{text-align:center;margin-bottom:20px;background:#ffffffc5}"
".logo{text-align:center;margin-bottom:15px}"
".logo img{max-width:160px}"
"label{font-size:14px;display:block;margin-top:12px;color:#050505}"
"input{width:100%;padding:10px;margin-top:5px;box-sizing:border-box;"
"border-radius:5px;border:1px solid #080808;background-color:#fff}"
"button{width:100%;padding:10px;margin-top:15px;box-sizing:border-box;"
"border-radius:5px;border:none;color:#fff;font-size:16px;cursor:pointer;"
"background:linear-gradient(135deg,#5b2aa8,#8f3ddb)}"
"</style></head><body>"
"<div class=\"container\"><div class=\"logo\">"
"<img src=\"icon.png\" alt=\"App Logo\"></div>"
"<label for=\"uname\"><b>Username</b></label>"
"<input type=\"text\" placeholder=\"username\" id=\"uname\" required><br>"
"<label for=\"pword\"><b>Password</b></label>"
"<input type=\"password\" placeholder=\"password\" id=\"pword\" required><br><br>"
"<button type=\"button\" onclick=\"formToLogin()\">Login</button>"
// "</div>"
"<script>"
"function formToLogin(){"
"var u=document.getElementById('uname').value;"
"var p=document.getElementById('pword').value;"
"var data='{'+"
"'\"username\":\"'+u+'\",\"password\":\"'+p+'\"}';"
"var x=new XMLHttpRequest();"
"x.onreadystatechange=function(){"
"if(this.readyState==4){"
"if(x.status==200)window.location='setting_page';"
"else alert('Incorrect Username or Password');}};"
"x.open('POST','/validate_auth');"
"x.send(data);}"
"</script>\n"
"</body></html>";

#endif