#ifndef PAGE_SETTING_H
#define PAGE_SETTING_H

const static char SettingHtml[] PROGMEM = 
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>Settings</title><style>"
"body{font-family:Arial,sans-serif;background-color:aliceblue;margin:0;padding:20px}"
".container{max-width:450px;margin:auto;padding:20px;border-radius:20px;"
"box-sizing:border-box;box-shadow:5px 10px 18px rgba(0,0,0,.5);"
"background-color:#fff;color:#ffffffc5}"
".container div{text-align:center;margin-bottom:20px;background: #ffffffc5}"
".logo{text-align:center;margin-bottom:15px}"
".logo img{max-width:160px}"
"label{font-size:14px;display:block;margin-top:12px;color:#050505}"
"select{width:100%;padding:10px;margin-top:5px;box-sizing:border-box;"
"border-radius:5px;border:1px solid #080808;background-color: #ffffff}"
"button{width:100%;padding:10px;margin-top:15px;box-sizing:border-box;"
"border-radius:5px;border:none;color:#fff;font-size:16px;cursor:pointer;"
"background:linear-gradient(135deg,#5b2aa8,#8f3ddb)}"
"</style></head><body onload=\"getPduId()\"><div class=\"container\">"
"<div class=\"logo\"><img src=\"icon.png\" alt=\"App Logo\"></div>"
"<label>PDU ID</label>"
"<select id=\"pduid\">"
"<option value=\"01\">01</option>"
"<option value=\"02\">02</option>"
"<option value=\"03\">03</option>"
"<option value=\"04\">04</option>"
"<option value=\"05\">05</option>"
"<option value=\"06\">06</option>"
"<option value=\"07\">07</option>"
"<option value=\"08\">08</option>"
"</select>"
"<button type=\"button\" onclick=\"formToUpdate()\">Update ID</button>"
"<script>"

"function getPduId(){"
"var pdu=document.getElementById('pduid');"
"var request=new XMLHttpRequest();"
"request.open('GET','/get_pduid');request.send();"
"request.onload=function(){"
"if(request.status==200){"
"var j=JSON.parse(request.responseText);"
"pdu.value=j.PDUID;"
"alert('Fetched last PDUID successfully');"
"}else{alert('Error: Connect to the Device.');}}"
"}"

"function formToUpdate(){"
"var p=document.getElementById('pduid').value;"
"var data='{'+'\"PDUID\":\"'+p+'\"}';"
"var x=new XMLHttpRequest();x.open('POST','/set_pduid');"
"x.onload=function(){"
"if(x.status==200){alert('Updated successfully');}"
"else{alert('Request failed');}};"
"x.send(data);}"
"</script>\n"
"</body></html>";

#endif