#ifndef PAGE_SETTING_H
#define PAGE_SETTING_H

const static char SettingHtml[] PROGMEM = 
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>Settings</title><style>"
"body{font-family:Arial,sans-serif;background-color:aliceblue;margin:0;padding:20px}"
".container{max-width:450px;margin:auto;padding:20px;border-radius:20px;"
"box-sizing:border-box;box-shadow:5px 10px 18px rgba(0,0,0,.5);"
"background-color:#fff;color:#ffffffc5}"
".container div{text-align:center;margin-bottom:20px;background: #ffffffc5}"
".logo{text-align:center;margin-bottom:15px}"
".logo img{max-width:160px}"
"label{font-size:14px;display:block;margin-top:12px;color:#050505}"
"input{width:100%;padding:9px;margin-top:5px;box-sizing:border-box;"
"border-radius:6px;border:1px solid #2a2a2a;background-color:#fff;color:#000}"
"input:focus{outline:none;border-color:#7a3cff}"
"select{width:100%;padding:10px;margin-top:5px;box-sizing:border-box;"
"border-radius:5px;border:1px solid #080808;background-color: #ffffff}"
"button{width:100%;margin-top:15px;padding:11px;"
"background:linear-gradient(135deg,#3a3db8,#7a3cff);color:#fff;"
"border:none;border-radius:8px;font-size:15px;font-weight:600;cursor:pointer;"
"transition:transform .1s ease,box-shadow .1s ease}"
"button.secondary{background:linear-gradient(135deg,#5b2aa8,#8f3ddb)}"
"button:hover{transform:translateY(-1px);box-shadow:0 4px 10px rgba(122,60,255,.4)}"
"</style></head><body onload=\"getSettings()\"><div class=\"container\">"
"<div class=\"logo\"><img src=\"icon.png\" alt=\"App Logo\"></div>"
"<label>PDU ID</label>"
"<select id=\"pduid\">"
"<option value=\"01\">01</option>"
"<option value=\"02\">02</option>"
"<option value=\"03\">03</option>"
"<option value=\"04\">04</option>"
"<option value=\"05\">05</option>"
"<option value=\"06\">06</option>"
"<option value=\"07\">07</option>"
"<option value=\"08\">08</option>"
"</select>"
"<label>Parameter Counts</label>"
"<select id=\"cnts\">"
"<option value=\"01\">01</option>"
"<option value=\"02\">02</option>"
"<option value=\"03\">03</option>"
"<option value=\"04\">04</option>"
"</select>"
"<label>Message ID</label>"
"<select id=\"msgid\">"
"<option value=\"01\">01</option>"
"<option value=\"02\">02</option>"
"<option value=\"03\">03</option>"
"<option value=\"04\">04</option>"
"<option value=\"05\">05</option>"
"<option value=\"06\">06</option>"
"<option value=\"07\">07</option>"
"<option value=\"08\">08</option>"
"</select>"
"<label>Display Size</label>"
"<select id=\"size\">"
"<option value=\"640mm\">640mm</option>"
"<option value=\"960mm\">960mm</option>"
"<option value=\"1600mm\">1600mm</option>"
"</select>"
"<label>Wifi SSID</label>"
"<input type=\"text\" placeholder=\"wifi ssid\" id=\"ssid\"maxlength=\"16\" required>"
"<label for=\"uname\">Username</label>"
"<input type=\"text\" placeholder=\"username\" id=\"uname\" maxlength=\"16\" required>"
"<label for=\"pword\">Password</label>"
"<input type=\"text\" placeholder=\"password\" id=\"pword\" maxlength=\"16\" required>"
"<button class=\"secondary\" type=\"button\" onclick=\"SaveSettings()\">Save</button>"
"<button class=\"secondary\" type=\"button\" onclick=\"goToReorder()\">Reorder Parameters</button>"
"<script>"

"function getSettings(){"
"var pdu=document.getElementById('pduid');"
"var cnt=document.getElementById('cnts');"
"var msg=document.getElementById('msgid');"
"var sze=document.getElementById('size');"
"var sid=document.getElementById('ssid');"
"var usr=document.getElementById('uname');"
"var psd=document.getElementById('pword');"
"var request=new XMLHttpRequest();"
"request.open('GET','/get_settings');request.send();"
"request.onload=function(){"
"if(request.status==200){"
"var j=JSON.parse(request.responseText);"
"pdu.value=j.PDUID;"
"cnt.value=j.CNTS;"
"msg.value=j.MSGID;"
"sze.value=j.SIZE;"
"sid.value=j.SSID;"
"usr.value=j.USER;"
"psd.value=j.PSWD;"
"alert('Fetched last PDUID successfully');"
"}else{alert('Error: Connect to the Device.');}}"
"}"

"function SaveSettings(){"
"var p=document.getElementById('pduid').value;"
"var c=document.getElementById('cnts').value;"
"var m=document.getElementById('msgid').value;"
"var s=document.getElementById('size').value;"
"var w=document.getElementById('ssid').value;"
"var u=document.getElementById('uname').value;"
"var d=document.getElementById('pword').value;"
"var data='{'+'\"PDUID\":\"'+p+'\",\"CNTS\":\"'+c+'\",\"MSGID\":\"'+m+'\",\"SIZE\":\"'+s+'\",\"SSID\":\"'+w+'\",\"USER\":\"'+u+'\",\"PSWD\":\"'+d+'\"}';"
"var x=new XMLHttpRequest();x.open('POST','/set_settings');"
"x.onload=function(){"
"if(x.status==200){alert('Updated successfully');}"
"else{alert('Request failed');}};"
"x.send(data);}"

"function goToReorder(){window.location='reorder_parameters';}"

"</script>\n"
"</body></html>";

#endif